add scoringtest.py to git-pre-commit
svn path=/trunk/KDE/kdegames/kajongg/; revision=1273146

diff --git a/git-pre-commit b/git-pre-commit
--- a/git-pre-commit
+++ b/git-pre-commit
@@ -87,6 +87,13 @@ then
 	echo "pylint must be quiet"
 	exit $result
 fi
+./scoringtest.py
+result=$?
+if [ $result -ne 0 ]
+then
+	echo "scoringtest.py failed"
+	exit $result
+fi
 cd ../..
 
 exec git diff-index --check --cached $against --
